from enum import Enum

class Currency_type(Enum):
    AUD = 'AUD'
    BRL = 'BRL'
    BGN = 'BGN'
    CNY = 'CNY'
    DKK = 'DKK'
    EUR = 'EUR'
    PHP = 'PHP'
    HKD = 'HKD'
    INR = 'INR'
    IDR = 'IDR'
    ISK = 'ISK'
    ILS = 'ILS'
    JPY = 'JPY'
    ZAR = 'ZAR'
    CAD = 'CAD'
    KRW = 'KRW'
    HUF = 'HUF'
    MYR = 'MYR'
    MXN = 'MXN'
    XDR = 'XDR'
    NOK = 'NOK'
    NZD = 'NZD'
    PLN = 'PLN'
    RON = 'RON'
    SGD = 'SGD'
    SEK = 'SEK'
    CHF = 'CHF'
    THB = 'THB'
    TRY = 'TRY'
    USD = 'USD'
    GBP = 'GBP'